Repository eu-digital-green-certificates/dgc-gateway, pull requests merged in 2021-05, with the labels that each got.

#34 Readme Local Deployment
  .gitignore
  README.md
  docker-compose.yml
  src/main/resources/logback-spring.xml
Labels: documentation

#36 docs: Update contributing
  CONTRIBUTING.md
Labels: documentation

#33 Feature: Audit Events for Upload
  src/main/java/eu/europa/ec/dgc/gateway/entity/AuditEventEntity.java
  src/main/java/eu/europa/ec/dgc/gateway/repository/AuditEventRepository.java
  src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateController.java
  src/main/java/eu/europa/ec/dgc/gateway/service/AuditService.java
  src/main/resources/db/changelog.xml
  src/main/resources/db/changelog/create-audit-table.xml
  src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateIntegrationTest.java
  src/test/java/eu/europa/ec/dgc/gateway/service/AuditServiceTest.java
Labels: enhancement

#37 Fix: CSCA Verification Error
  src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java
Labels: bug

#40 Improve documentation
  README.md
Labels: documentation

#45 Fix: Certificate Hash in Audit Events
  src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateController.java
  src/main/java/eu/europa/ec/dgc/gateway/service/AuditService.java
  src/test/java/eu/europa/ec/dgc/gateway/service/AuditServiceTest.java
Labels: bug

#49 Feature: Automatic Generation of Third Party Notices
  .github/workflows/ci-main-docker.yml
  .github/workflows/ci-main.yml
  THIRD-PARTY-NOTICES
  THIRD-PARTY.md
  pom.xml
  src/main/java/eu/europa/ec/dgc/gateway/entity/AuditEventEntity.java
  src/main/java/eu/europa/ec/dgc/gateway/exception/DgcgResponseException.java
  src/main/java/eu/europa/ec/dgc/gateway/model/TrustList.java
  src/main/java/eu/europa/ec/dgc/gateway/model/TrustListType.java
  src/main/java/eu/europa/ec/dgc/gateway/repository/AuditEventRepository.java
  src/main/java/eu/europa/ec/dgc/gateway/restapi/converter/CertificateTypeEnumConverter.java
  src/main/java/eu/europa/ec/dgc/gateway/restapi/mapper/TrustListMapper.java
  src/main/java/eu/europa/ec/dgc/gateway/service/AuditService.java
  src/test/java/eu/europa/ec/dgc/gateway/service/AuditServiceTest.java
  src/test/java/eu/europa/ec/dgc/gateway/service/TrustListServiceTest.java
  templates/third-party.ftl
Labels: enhancement

#48 Fix: Missing Version in OpenAPI
  src/main/java/eu/europa/ec/dgc/gateway/DgcGatewayApplication.java
  src/main/java/eu/europa/ec/dgc/gateway/config/OpenApiConfig.java
Labels: bug

#46 Fix Response Code for Invalid Authorization
  src/main/java/eu/europa/ec/dgc/gateway/restapi/filter/CertificateAuthenticationFilter.java
  src/test/java/eu/europa/ec/dgc/gateway/restapi/filter/CertAuthFilterTest.java
Labels: bug

#44 Doc: Add Link to OpenAPI Spec
  README.md
Labels: documentation

#53 Fix: Typo in OpenAPI Spec
  src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
Labels: bug, documentation

#54 Fix: Add BouncyCastleProvider to JavaSecurity
  src/main/java/eu/europa/ec/dgc/gateway/config/BouncyCastleConfig.java
Labels: bug

#56 Update DGC Lib
  pom.xml
  src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
  src/main/java/eu/europa/ec/dgc/gateway/restapi/mapper/GwTrustListMapper.java
Labels: enhancement

#65 Add Authentication Header to Swagger UI
  README.md
  src/main/java/eu/europa/ec/dgc/gateway/config/OpenApiConfig.java
  src/main/resources/application-local.yml
Labels: enhancement

#64 Add Alias for Delete/Revoke Endpoint
  src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateController.java
Labels: enhancement

#67 Fix: Newline in Logging
  docs/software-design-dgc-gateway.md
  src/main/java/eu/europa/ec/dgc/gateway/config/ErrorHandler.java
  src/main/java/eu/europa/ec/dgc/gateway/config/MdcCleanupInterceptor.java
  src/main/java/eu/europa/ec/dgc/gateway/config/WebMvcConfig.java
  src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateController.java
  src/main/java/eu/europa/ec/dgc/gateway/service/AuditService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/TrustedPartyService.java
  src/main/resources/logback-spring.xml
Labels: bug, documentation

#66 Update Dependencies
  pom.xml
Labels: enhancement

#69 Update DGC-Lib
  pom.xml
Labels: enhancement

#68 Add Cert Hashes to Logging
  docs/software-design-dgc-gateway.md
  src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java
Labels: documentation, enhancement

#70 Add Logging for Downloaded Keys
  docs/software-design-dgc-gateway.md
  src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
Labels: enhancement

#71 Add Check for Double KID
  src/main/java/eu/europa/ec/dgc/gateway/repository/SignerInformationRepository.java
  src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java
  src/test/java/eu/europa/ec/dgc/gateway/service/SignerInformationServiceTest.java
Labels: enhancement

#72 Fix MDC Parameter name for Verification Errors
  docs/software-design-dgc-gateway.md
  src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateController.java
Labels: bug, documentation
