Repository eu-digital-green-certificates/dgc-gateway, pull requests merged in 2022-03, with the labels that each got.

#160 Add Trusted Issuer
  src/main/java/eu/europa/ec/dgc/gateway/entity/TrustedIssuerEntity.java
  src/main/java/eu/europa/ec/dgc/gateway/repository/TrustedIssuerRepository.java
  src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
  src/main/java/eu/europa/ec/dgc/gateway/restapi/dto/TrustedIssuerDto.java
  src/main/java/eu/europa/ec/dgc/gateway/restapi/mapper/GwTrustedIssuerMapper.java
  src/main/java/eu/europa/ec/dgc/gateway/service/TrustedIssuerService.java
  src/main/resources/db/changelog.xml
  src/main/resources/db/changelog/add-trusted-issuer-table.xml
  src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListIntegrationTest.java
  src/test/java/eu/europa/ec/dgc/gateway/service/TrustedIssuerServiceTest.java
  src/test/java/eu/europa/ec/dgc/gateway/testdata/TrustedIssuerTestHelper.java
  src/test/java/eu/europa/ec/dgc/gateway/testdata/TrustedPartyTestHelper.java
Labels: enhancement

#166 flag SignerInformationEntity for deletion
  pom.xml
  src/main/java/eu/europa/ec/dgc/gateway/config/DgcConfigProperties.java
  src/main/java/eu/europa/ec/dgc/gateway/entity/SignerInformationEntity.java
  src/main/java/eu/europa/ec/dgc/gateway/repository/SignerInformationRepository.java
  src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationCleanUpService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/TrustListService.java
  src/main/resources/application.yml
  src/main/resources/db/changelog.xml
  src/main/resources/db/changelog/alter-signer-information-for-deletion.xml
  src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateMigrationControllerTest.java
  src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListIntegrationTest.java
  src/test/java/eu/europa/ec/dgc/gateway/service/SignerInformationCleanUpServiceTest.java
  src/test/java/eu/europa/ec/dgc/gateway/service/SignerInformationServiceTest.java
  src/test/java/eu/europa/ec/dgc/gateway/testdata/SignerInformationTestHelper.java
Labels: enhancement

#162 feat: unprivileged docker user
  Dockerfile
Labels: enhancement

#168 doc: security advice using provided configuration
  README.md
Labels: documentation

#167 feat: revocation batches marked for deletion are not returned for migration
  src/main/java/eu/europa/ec/dgc/gateway/service/RevocationListService.java
  src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateMigrationControllerTest.java
Labels: enhancement

#169 feat: dsc delta download extension
  pom.xml
  src/main/java/eu/europa/ec/dgc/gateway/config/DgcConfigProperties.java
  src/main/java/eu/europa/ec/dgc/gateway/entity/SignerInformationEntity.java
  src/main/java/eu/europa/ec/dgc/gateway/repository/SignerInformationRepository.java
  src/main/java/eu/europa/ec/dgc/gateway/repository/TrustedPartyRepository.java
  src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
  src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationCleanUpService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/TrustListService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/TrustedPartyService.java
  src/main/java/eu/europa/ec/dgc/gateway/utils/ListUtils.java
  src/main/resources/application.yml
  src/main/resources/db/changelog.xml
  src/main/resources/db/changelog/alter-signer-information-for-deletion.xml
  src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateMigrationControllerTest.java
  src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListIntegrationTest.java
  src/test/java/eu/europa/ec/dgc/gateway/service/SignerInformationCleanUpServiceTest.java
  src/test/java/eu/europa/ec/dgc/gateway/service/SignerInformationServiceTest.java
  src/test/java/eu/europa/ec/dgc/gateway/service/TrustListServiceTest.java
  src/test/java/eu/europa/ec/dgc/gateway/service/TrustedPartyServiceTest.java
  src/test/java/eu/europa/ec/dgc/gateway/testdata/SignerInformationTestHelper.java
  src/test/java/eu/europa/ec/dgc/gateway/testdata/TrustedPartyTestHelper.java
Labels: enhancement

#171 Fix: Add Embedded Signature for DSC Migration
  pom.xml
  src/main/java/eu/europa/ec/dgc/gateway/restapi/converter/CmsCertificateMessageConverter.java
  src/main/java/eu/europa/ec/dgc/gateway/restapi/dto/CmsPackageDto.java
  src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java
  src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateMigrationControllerTest.java
Labels: bug

#177 Fix: Reupload of DSC
  src/main/java/eu/europa/ec/dgc/gateway/repository/SignerInformationRepository.java
  src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java
  src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateIntegrationTest.java
Labels: bug

#178 Fix: Add UUID and Domain to TrustedIssuer
  src/main/java/eu/europa/ec/dgc/gateway/entity/TrustedIssuerEntity.java
  src/main/java/eu/europa/ec/dgc/gateway/restapi/dto/TrustedIssuerDto.java
  src/main/resources/db/changelog.xml
  src/main/resources/db/changelog/add-uuid-and-domain-for-trusted-issuer.xml
Labels: bug

#179 Feat: Publication
  docker-compose.yml
  lombok.config
  src/main/java/eu/europa/ec/dgc/gateway/client/AssetManagerClient.java
  src/main/java/eu/europa/ec/dgc/gateway/client/AssetManagerClientConfig.java
  src/main/java/eu/europa/ec/dgc/gateway/config/DgcConfigProperties.java
  src/main/java/eu/europa/ec/dgc/gateway/config/DgcKeyStore.java
  src/main/java/eu/europa/ec/dgc/gateway/model/AssetManagerSynchronizeResponseDto.java
  src/main/java/eu/europa/ec/dgc/gateway/service/PublishingService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/TrustedIssuerService.java
  src/main/java/eu/europa/ec/dgc/gateway/service/TrustedPartyService.java
  src/main/resources/application.yml
  src/main/resources/publication/License.txt
  src/main/resources/publication/Readme.txt
  src/test/java/eu/europa/ec/dgc/gateway/publishing/ArchivePublishingTest.java
  src/test/java/eu/europa/ec/dgc/gateway/publishing/PublishingDisabledTest.java
  src/test/java/eu/europa/ec/dgc/gateway/testdata/DgcTestKeyStore.java
  src/test/java/eu/europa/ec/dgc/gateway/testdata/TrustedIssuerTestHelper.java
  src/test/java/eu/europa/ec/dgc/gateway/testdata/TrustedPartyTestHelper.java
  src/test/resources/application.yml
Labels: enhancement
